name: shapepipe
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.2.4
  - astromatic-psfex==3.21.1
  - astromatic-source-extractor==2.25.0
  - astropy==5.1
  - automake
  - autoconf
  - cmake
  - galsim
  - joblib
  - libtool
  - matplotlib
  - ngmix==2.3.0
  - numba
  - numpy==1.22
  - pip:
    - cs_util
    - mccd==1.2.3
    - modopt
    - PyQt5
    - pyqtgraph
    - reproject
    - skaha
    - sip_tpv
    - sf_tools
    - sqlitedict
    - termcolor
    - tqdm
    - treecorr
    - git+https://github.com/tobias-liaudat/Stile@v0.1
